### ISSUE TITLE
TLS error when transfering component version between registries including resources v0.16.0

### ISSUE THREAD

**Issue by markrexwinkel** [open-component-model/ocm#972]
**What happened**:
When transfering a component version including its resources, TLS errors occur when transfering the resources.

**What you expected to happen**:
Resources should be transfered without errors.

**How to reproduce it (as minimally and precisely as possible)**:
I created a reproduction in the following git repo: [https://github.com/markrexwinkel/ocm-ca-cert-bug-repro](https://github.com/markrexwinkel/ocm-ca-cert-bug-repro)

**Anything else we need to know**:
The error did not occur with version v0.15.0. It seems that moving to oras is introducing this regression.
The example uses an external image resource but it also happens with resources local to the component version.
It looks like root CAs are not set correctly or getting mixed up.

>NOTE: the reproduction example references v0.15.0 by default, so the code should run without errors. After changing the version to v0.16.0 the error will occur.
 
**Environment**:
Tested on Ubuntu on WSL2 Windows 11 and on Windows 11 only.

**Comment by Skarlso** [comment]
Can you test this PR please? https://github.com/open-component-model/ocm/pull/968

Or rather can you provide reproducing steps please including the component?

**Comment by Skarlso** [comment]
How are you using the library?

**Comment by markrexwinkel** [comment]
> How are you using the ocm tool?
> 
> Please paste in some commands so I can test it locally instead of endless back end forth on the issue. :)

I use OCM as a library. If you clone [my repo](https://github.com/markrexwinkel/ocm-ca-cert-bug-repro) you can run the code in `main.go`. To setup the registries please run `docker compose up -d` in the root of the repo.

```bash
git clone https://github.com/markrexwinkel/ocm-ca-cert-bug-repro.git
cd ocm-ca-cert-bug-repro
docker compose up -d
```

The repo references v0.15.0. To use your branch you can add a `replace` in the `go.mod` like this:

```
replace ocm.software/ocm => <path to your local ocm source>
```

**Comment by Skarlso** [comment]
Okay, reproduced.

```
test.org/test:1.0.0: transferring resource 0: unable to add blob (component test.org/test:1.0.0 resource helminstaller): exploding OCI artifact resource blob ([open-component-model/ocm/ocm.software/toi/installers/helminstaller/helminstaller:0.4.0] namespace open-component-model/ocm/ocm.software/toi/installers/helminstaller/helminstaller: transfer artifact): getting indexed artifact sha256:e9ebbeca844819f8ae5ad635a46c06c8c0f7b65d94fbb6d470f12aca8092d734: Head "https://ghcr.io/v2/open-component-model/ocm/ocm.software/toi/installers/helminstaller/helminstaller/manifests/sha256:e9ebbeca844819f8ae5ad635a46c06c8c0f7b65d94fbb6d470f12aca8092d734": tls: failed to verify certificate: x509: certificate signed by unknown authority
exit status 1

```

Thanks, I'll take a look at what's up.

**Comment by Skarlso** [comment]
Weird. I'm doing the same thing that OCM did back with docker. How annoying.

**Comment by markrexwinkel** [comment]
Another issue (and this should probably be another github issue) is that plain http registries so `http://localhost:5000` (no TLS configured) is not working because the oras repository that is created has PlainHTTP not set. I temporary worked around that by adding the following line in `api/oci/extensions/repositories/ocireg/repository.go`:

```go
func (r *RepositoryImpl) getResolver(ref string, comp string) (registry.Repository, error) {
    ...
    if r.info.Scheme == "https" {
        ...
    } else {
        client = http.DefaultClient
	repo.PlainHTTP = true
    }
    ...
}
```

**Comment by Skarlso** [comment]
Yah, I did that in the attached PR. ( expect for the repo.PlainHTTP... ).

**Comment by Skarlso** [comment]
Okay, almost there.. :D Now I'm having a different problem. :D

**Comment by Skarlso** [comment]
Fixed it. :)

**Comment by markrexwinkel** [comment]
I pulled the latest version of your branch but I get still the same tls error.

**Comment by Skarlso** [comment]
I haven't pushed the fix yet. :) It's complicated. :D There are other problems right now I'm fixing.

**Comment by Skarlso** [comment]
Apparently, it's trying to push into the manifest layer instead of the blob layer. I need a nice way to determine where to push things.

**Comment by Skarlso** [comment]
Okay try it now please. :)

**Comment by markrexwinkel** [comment]
Now I got another error:

```bash
2024-10-17T16:12:56+02:00 info    [ocm/transfer] "transferring version" history= version=test.org/test:1.0.0
2024-10-17T16:12:56+02:00 info    [ocm/transfer] "  transferring references" history= version=test.org/test:1.0.0
2024-10-17T16:12:56+02:00 info    [ocm/transfer] "  transferring resources" history= version=test.org/test:1.0.0
test.org/test:1.0.0: transferring resource 0: unable to add blob (component test.org/test:1.0.0 resource helminstaller): exploding OCI artifact resource blob ([open-component-model/ocm/ocm.software/toi/installers/helminstaller/helminstaller:0.4.0] namespace open-component-model/ocm/ocm.software/toi/installers/helminstaller/helminstaller: transfer artifact): transferring index artifact: failed to push tag 0.4.0: failed to push reference: PUT "https://localhost:5001/v2/open-component-model/ocm/ocm.software/toi/installers/helminstaller/helminstaller/manifests/0.4.0": response status code 400: manifest blob unknown: blob unknown to registry: sha256:e9ebbeca844819f8ae5ad635a46c06c8c0f7b65d94fbb6d470f12aca8092d734; manifest blob unknown: blob unknown to registry: sha256:90b724c5091571ce23d0600e705011dc167805d913f9c9a2fb6254fb32070e99
```

**Comment by Skarlso** [comment]
BTW. `ghcr` works flawlessly... 

```
go run main.go
Create context
Add credentials
Create component version at  /var/folders/gh/m47qw8n917n9gym8n_7ttlsc0000gn/T/3889675048/ca
Transfer ctf to source registry
 2024-10-17T17:03:45+02:00 info    [ocm/transfer] "transferring version" history= version=test.org/test:1.0.0
 2024-10-17T17:03:45+02:00 info    [ocm/transfer] "  transferring references" history= version=test.org/test:1.0.0
Tranfer component version from source to destination registry
 2024-10-17T17:03:46+02:00 info    [ocm/transfer] "transferring version" history= version=test.org/test:1.0.0
 2024-10-17T17:03:46+02:00 info    [ocm/transfer] "  transferring references" history= version=test.org/test:1.0.0
 2024-10-17T17:03:46+02:00 info    [ocm/transfer] "  transferring resources" history= version=test.org/test:1.0.0
 2024-10-17T17:04:31+02:00 info    [ocm/transfer] "  transferring sources" history= version=test.org/test:1.0.0
 2024-10-17T17:04:31+02:00 info    [ocm/transfer] "  adding component version" history= version=test.org/test:1.0.0

```

So this is a docker registry problem.. UGH.

**Comment by Skarlso** [comment]
Okay, the new version should work now.

**Comment by markrexwinkel** [comment]
Nice! I tried it and it works, great work, thx!

**Comment by Skarlso** [comment]
Yaaay, thanks for confirming! :)

**Comment by Skarlso** [comment]
https://github.com/open-component-model/ocm/actions/runs/11404171246

v0.16.1 released with this patch. :)
